sn_ia:
  - Ia
  - Ia-pec
  - Ia-02cx
  - Ia-91b
  - Ia-18byg
  - Ia-CSM
  - Type I
  - Ia-CSM?
  - Ia-03fg
  - Ia-91bg
  - Ia-91bg?
  - Ia-91T
  - Ia-norm
  - Iax
  - Ia-03fg
  - Ia?
  - Ia-91T-like
  - Ia-pec
  - Iax[02cx-like]

tde:
  - Tidal Disruption Event
  - TDE

sn_other:
  - IIP
  - II
  - Type II
  - IIb?
  - IIn
  - Ibn?
  - Supernova
  - SLSN-I
  - Ic-BL?
  - Ic
  - Ic-SLSN
  - SLSN-II
  - Ib/c?
  - Ic?
  - IIn?
  - Ib
  - Ic-BL
  - SLSN I
  - Ib/c
  - IIb
  - II-norm
  - Ibn
  - SLSN-I?
  - II?
  - IIb-pec
  - SLSN-I.5
  - Icn
  - Ib?
  - I
  - SN

bogus:
  - bogus
  - duplicate
  - bogus?
  - CV
  - varstar
  - rock

unclass:
  - "-"
  - None

other:
  - FBOT
  - LRN
  - ILRT
  - Ca-rich
  - LRN?
  - afterglow
  - Galaxy

agn_star:
  - nova
  - CV?
  - varstar
  - Varstar
  - AGN
  - QSO
  - nova?
  - star
  - LBV
  - NLSy1?
  - NLSy1
  - CLAGN
  - AGN?
  - NLS1
  - galaxy
  - Seyfert
  - AM CVn
  - var
  - blazar

star:
  - nova
  - CV?
  - varstar
  - Varstar
  - nova?
  - star
  - LBV
  - var

axislabels:
  temp: Temperature (log K)
  d_temp: Temperature change (K)
  rise: Rise time (log day)
  decay: Decay time (log day)
  red_chisq: TDE fit red. chisq.
  salt_red_chisq: SALT fit red. chisq.
  wise_w1w2: Wise W1-W2
  wise_w2w3: Wise W2-W3

cutlabels:
  full: All cuts
  temp: temperature (based on TDE fit)
  wise_noagn: remove AGN (based on WISE colors)
  wise_keepagn: retain only AGN (based on WISE colors)
  bayes: "exactly 1 flare"
  nocut: "no cuts applied (only bogus veto and TDE fit success)"
  snia: "rise/decay based Ia cut"
  chisq: "chisq. cut (TDE $<$ SALT)"
  risedecay: "TDE-fit rise and decay time"
  coredist: "core distance $<$ 0.4 arcsec"
  sgscore: "sgscore $<$ 0.4"
  milliquas_noagn: "remove AGN (based on Milliquas match)"
  milliquas_keepagn: "retain only AGN (based on Milliquas match)"

classlabels:
  all: All classifications
  snia: SN Ia
  tde: TDE
  agn_star: AGN/star
  sn_other: SN (no Ia)
  unclass: Unclass.
  other: Other


fritz_queries:
    snia: fritz_class in @config['fritz_sn_ia']
    unclass: fritz_class not in @config['fritz_sn_ia'] and fritz_class not in @config['fritz_tde'] and fritz_class not in @config['fritz_sn_other'] and fritz_class not in @config['fritz_other'] and fritz_class not in @config['fritz_agn_star']
    sn_other: fritz_class in @config['fritz_sn_other']
    agn_star: fritz_class in @config['fritz_agn_star']
    other: fritz_class in @config['fritz_other']
    tde: fritz_class in @config['fritz_tde']

selections: &id001
  all: "rise > -1e99 or rise.isnull()" # fake cut, no empty df.query is allowed
  # boundary: "rise>0.1 and rise < 3 and decay > 0.1 and decay<4 and wise_w2w3 < 900 and wise_w1w2 < 900 and red_chisq < 1000 and salt_red_chisq < 600 "
  boundary: "rise>0.1 and rise < 3 and decay > 0.1 and decay<4 "
  bogus: "fritz_class not in @config['bogus'] and fritz_class not in @config['unclass'] "
  bogusbts: "type not in @config['bogus'] and type not in @config['unclass'] "
  risedecay: "rise>0.8 and rise<2.05 and decay>1.1 and decay<3 "
  chisq: "red_chisq<6 and red_chisq < salt_red_chisq "
  gold_chisq: "red_chisq < 5 and salt_red_chisq < 75 and red_chisq < salt_red_chisq "
  flaring_chisq: "red_chisq<12 and salt_red_chisq<120 "
  temp: "temp > 3.9 and temp < 4.4 and d_temp>-100 and d_temp < 150 "
  gold_temp: "3.5<temp<4.3 and -100<d_temp<120 "
  flaring_temp: "3.5<temp<4.3 and -80<d_temp<200 "
  snia: "snia_cut < decay "
  overlapping_regions: "overlapping_regions == 1 "
  # wise: "((wise_w1w2<0.3 or wise_w1w2>1.8) or (wise_w2w3 <1.5 or wise_w2w3>3.5)) "
  wise_outside_box: "in_wise_agn_box == False"
  wise_in_box: "in_wise_agn_box == True"
  milliquas_no_agn: "crossmatch_Milliquas_type.isnull() "
  milliquas_keep_agn: "not crossmatch_Milliquas_type.isnull() "
  gold_wise: "(not (wise_w1w2<-0.1 or wise_w1w2>1.1 or wise_w2w3 <1.4 or wise_w2w3>4.3)) "
  flaring_wise: "(not (wise_w1w2<-0.1 or wise_w1w2>1.1 or wise_w2w3 <1.5 or wise_w2w3>4) "
  gold_risedecay: "0.9<rise<2.5 and 1.5<decay<3.8 "
  flaring_risedecay: "1.4<decay<4 and 0.8<rise<2.5 "
  flaring: "ztfid in @flaring_ztfids "
  coredist: "distnr_distnr < 0.4 "
  sgscore: "crossmatch_sgscore_sgscore < 0.4 "
  # sgscore: "rise > -1e99 or rise.isnull() "

    # # that's the one for dtemp = 15k, evolution from peak, bolcorr
    # tde_selection_finetuned = "temp > 3.93 and temp < 4.38 and d_temp>-90 and d_temp < 140 and rise>0.85 and rise<2.05 and decay>1.1 and decay<3 and red_chisq<6 and red_chisq < salt_red_chisq"

    # tde_selection_full = "temp > 3.9 and temp < 4.4 and d_temp>-100 and d_temp < 150 and rise>0.8 and rise<2.05 and decay>1.1 and decay<3 and red_chisq<6 and red_chisq < salt_red_chisq"

cuts:
  full: 
    - risedecay
    - sgscore
    - coredist
    - chisq
    - temp
    - snia
    - overlapping_regions
    - milliquas_no_agn
  goldfull:
    - coredist
    - sgscore
    - gold_risedecay
    - gold_chisq
    - gold_temp
    - overlapping_regions
    - gold_wise
  flaringfull:
    - coredist
    - flaring
    - flaring_risedecay
    - flaring_chisq
    - flaring_temp
    - flaring_wise
  coredist:
    - coredist
  nocut:
    - all
  milliquas_noagn:
    - milliquas_no_agn
  milliquas_keepagn:
    - milliquas_keep_agn
  boundary:
    - boundary
  wise_noagn:
    - wise_outside_box
  wise_keepagn:
    - wise_in_box
  goldwise:
    - gold_wise
  sgscore:
    - sgscore
  flaringwise:
    - flaring_wise
  snia:
    - snia
  temp:
    - temp
  goldtemp:
    - gold_temp
  flaringtemp:
    - flaring_temp
  risedecay:
    - risedecay
  goldrisedecay:
    - gold_risedecay
  flaringrisedecay:
    - flaring_risedecay
  chisq:
    - chisq
  goldchisq:
    - gold_chisq
  flaringchisq:
    - flaring_chisq
  bayes:
    - overlapping_regions
  flaring:
    - flaring

classes:
  snia: "classif == 'snia' "
  unclass: "classif == 'unclass' "
  sn_other: "classif == 'sn_other' "
  tde: "classif == 'tde' "
  other: "classif == 'other' "
  agn_star: "classif == 'other' "

colordict:
  unclass: "#5799c7"
  other: "#ff9f4a"
  snia: "#61b861"
  tde: "#e15d5e"
  sn_other: "#af8dce"
  agn_star: "#a98078"

colordict_highlight:
  unclass: "#5799c7"
  other: "#ff9f4a"
  snia: green
  tde: red
  sn_other: darkviolet
  agn_star: peru

pl_props:
    unclass: 
      m: +
      s: 11
      c: blue
      a: 1 
      l: Unclass.
      order: 1
    snia:
      m: x
      s: 8
      c: green
      a: 1
      l: SN Ia
      order: 2
    sn_other:
      m: s
      s: 8
      c: orange
      a: 1
      l: SN (no Ia)
      order: 3
    tde:
      m: '*'
      s: 30
      c: red
      a: 1
      l: TDE
      order: 100
    gold:
      m: 'X'
      s: 30
      c: gold
      a: 1
      l: Gold
      order: 101
    other:
      m: .
      s: 8
      c: brown
      a: 1
      l: Other
      order: 3
    agn_star:
      m: h
      s: 8
      c: black
      a: 1
      l: AGN/Star
      order: 4
