fritz_sn_ia:
  - Ia
  - Ia-pec
  - Ia-02cx
  - Ia-91b
  - Ia-18byg
  - Ia-CSM
  - Type I
  - Ia-CSM?
  - Ia-03fg
  - Ia-91bg
  - Ia-91bg?
  - Ia-91T
  - Ia-norm
  - Iax
  - Ia-03fg
  - Ia?

fritz_tde:
  - Tidal Disruption Event
  - TDE

fritz_sn_other:
  - IIP
  - II
  - Type II
  - IIb?
  - IIn
  - Ibn?
  - Supernova
  - SLSN-I
  - Ic-BL?
  - Ic
  - Ic-SLSN
  - SLSN-II
  - Ib/c?
  - Ic?
  - IIn?
  - Ib
  - Ic-BL
  - SLSN I
  - Ib/c
  - IIb
  - II-norm
  - Ibn
  - SLSN-I?
  - II?
  - IIb-pec
  - SLSN-I.5
  - Icn
  - Ib?

fritz_bogus:
  - bogus
  - duplicate
  - bogus?
  - CV
  - varstar
  - rock

fritz_unclass:
  - "-"

fritz_other:
  - FBOT
  - LRN
  - ILRT
  - Ca-rich
  - LRN?
  - afterglow

fritz_agn_star:
  - nova
  - CV?
  - varstar
  - AGN
  - QSO
  - nova?
  - star
  - NLSy1?
  - NLSy1
  - CLAGN
  - AGN?
  - NLS1
  - galaxy
  - Seyfert
  - AM CVn
  - var
  - blazar

tns_sn_ia:
  - SN Ia
  - SN Ia-91T-like
  - SN Ia-pec
  - SN Ia-CSM
  - SN Iax[02cx-like]

tns_sn_other:
  - SN II
  - SN IIn
  - SLSN-II
  - SN Ic
  - SLSN-I
  - SN IIP
  - SN Ib
  - SN Ic-BL
  - SN Ib/c
  - SN IIb
  - SN I
  - SN
  - SN Ibn

axislabels:
  temp: Temperature (log K)
  d_temp: Temperature change (K)
  rise: Rise time (log day)
  decay: Decay time (log day)
  red_chisq: TDE fit red. chisq.
  salt_red_chisq: SALT fit red. chisq.
  wise_w1w2: Wise W1-W2
  wise_w2w3: Wise W2-W3

fritz_queries:
    snia: fritz_class in @config['fritz_sn_ia']
    unclass: fritz_class not in @config['fritz_sn_ia'] and fritz_class not in @config['fritz_tde'] and fritz_class not in @config['fritz_sn_other'] and fritz_class not in @config['fritz_other'] and fritz_class not in @config['fritz_agn_star']
    sn_other: fritz_class in @config['fritz_sn_other']
    agn_star: fritz_class in @config['fritz_agn_star']
    other: fritz_class in @config['fritz_other']
    tde: fritz_class in @config['fritz_tde']

pl_props:
    unclass: 
      m: .
      s: 1
      c: blue
      a: 0.7
      l: unclass.
      order: 1
    snia:
      m: .
      s: 8
      c: green
      a: 1
      l: SN Ia
      order: 2
    sn_other:
      m: .
      s: 8
      c: orange
      a: 1
      l: SN other
      order: 3
    tde:
      m: '*'
      s: 30
      c: red
      a: 1
      l: TDE
      order: 100
    gold:
      m: 'X'
      s: 30
      c: gold
      a: 1
      l: Gold
      order: 101
    other:
      m: .
      s: 8
      c: brown
      a: 1
      l: other
      order: 3
    agn_star:
      m: .
      s: 8
      c: black
      a: 1
      l: AGN/star
      order: 4
